name: JSON Change Notification

on:
  push:
    branches:
      - main
    paths:
      - 'active/**/*.json'

jobs:
  notify_backend:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: https://powerful-accurate-bluebird.ngrok-free.app/allocator/create

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed JSON files
        id: get_changed_files
        run: |
          echo "::set-output name=files_changed::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- 'active/**/*.json')"

      - name: Send POST request
        run: |
          JSON_DATA='{"files_changed": "${{ steps.get_changed_files.outputs.files_changed }}"}'
          echo "JSON sent to the back-end: $JSON_DATA"
          curl -X POST -H "Content-Type: application/json" -d "$JSON_DATA" $BACKEND_URL
