name: Notify Backend on JSON Change

on:
  push:
    paths:
      - 'active/**/*.json'
    branches:
      - main

jobs:
  notify-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set BACKEND_URL
        run: echo "BACKEND_URL=https://powerful-accurate-bluebird.ngrok-free.app/allocator/create" >> $GITHUB_ENV

      - name: Find changed JSON files in Active folder
        id: find_json
        run: |
          echo "Finding changed JSON files..."
          FILES_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^active/.*\.json$')
          FILES_JSON=$(echo "$FILES_CHANGED" | jq -R . | jq -s .)
          echo "FILES_JSON=${FILES_JSON}" >> $GITHUB_ENV
      
      - name: Notify Backend Service
        if: env.FILES_JSON != '[]'
        run: |
          curl --header "Content-Type: application/json" \
               --request POST \
               --data "{\"files_changed\":${FILES_JSON}}" \
               "${BACKEND_URL}/update"
        env:
          FILES_JSON: ${{ env.FILES_JSON }}