name: Notify Backend on JSON Changes (main branch)

on:
  push:
    branches: [ main ]
    paths:
      - 'active/**/*.json'  # Detect changes and new files within "active" folder

jobs:
  notify-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Get all JSON files (changed and new)
        id: all_files
        run: |
          git diff --name-only --cached HEAD~1...HEAD | grep '^active/' | grep '\.json$'  # Find changed files
          echo " $(git ls-files active/**/*.json)" | tr '\n' ' '  # Find all files (including new)

      - name: Filter changed and new JSON files
        id: changed_files
        run: |
          all_files=$(echo ${{ steps.all_files.outputs.all_files }})
          changed_files=$(echo "''")  # Initialize empty array variable

          for file in $all_files; do
            if git diff --cached HEAD~1...HEAD -- "$file" &> /dev/null; then
              changed_files="$changed_files,\"$file\""
            fi
          done

          # Remove leading comma if any files were changed
          changed_files=${changed_files:1}
          echo "::set-output name=changed_files::[$changed_files]"

      - name: Print JSON data (for debugging)
        run: |
          echo "Sending data to backend:"
          echo '{"files_changed": '${{ steps.changed_files.outputs.changed_files }}}'

      - name: Notify backend
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://powerful-accurate-bluebird.ngrok-free.app/allocator/create
          method: POST
          data: '{"files_changed": ${{ steps.changed_files.outputs.changed_files }}}'
