name: Check Allocator Signers

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  check-signers:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: https://fp-core.dp04sa0tdc6pk.us-east-1.cs.amazonlightsail.com

    steps:
      - name: Check Signers
        run: |
          curl --header "Content-Type: application/json" \
               --request POST \
               "${BACKEND_URL}/allocator/signersCheck"
